[build]
  command = "npm install && cd frontend && npm install && npm run build"
  publish = "frontend/dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/tasks/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/api/tasks/create/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/api/tasks/update/:id/*"
  to = "/.netlify/functions/:id/:splat"
  status = 200

[[redirects]]
  from = "/api/tasks/delete/:id/*"
  to = "/.netlify/functions/:id/:splat"
  status = 200

[[redirects]]
  from = "/api/tasks/complete/:id/*"
  to = "/.netlify/functions/:id/:splat"
  status = 200
