[build]
  command = "npm install && cd frontend && npm install && npm run build"
  publish = "frontend/dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/tasks/addTask/*"
  to = "/.netlify/functions/addTask"
  status = 200

[[redirects]]
  from = "/api/tasks/completeTask/*"
  to = "/.netlify/functions/completeTask"
  status = 200

[[redirects]]
  from = "/api/tasks/deleteTask/*"
  to = "/.netlify/functions/deleteTask"
  status = 200

[[redirects]]
  from = "/api/tasks/getAllTask/*"
  to = "/.netlify/functions/getAllTask"
  status = 200

[[redirects]]
  from = "/api/tasks/updateTask/*"
  to = "/.netlify/functions/updateTask"
  status = 200
